extends Node3D
## Final store level root (docs/ARCHITECTURE.md §6 level contract, §7 layout).
## The scene is GENERATED by tools/build_store_level.gd — edit the generator, not the .tscn:
##   godot --headless --path . -s res://tools/build_store_level.gd
##
## The navmesh is baked with 0.1 m cells (doorways are 1.2 m, agents 0.4 m radius). The project's
## default navigation map uses the same cell size/height (project.godot); this re-applies them
## to the map in case a host changed the world's map settings before the level loads.


## The art's static breaker box sits where the breaker_panel prop (with its opening door) is
## placed; only the prop is shown.
const HIDDEN_ART := [^"NavigationRegion3D/StoreInterior/BackOfHouse/BreakerPanel_Static"]


func _ready() -> void:
	for path in HIDDEN_ART:
		var node := get_node_or_null(path) as Node3D
		if node:
			node.visible = false


func _enter_tree() -> void:
	var region := get_node_or_null(^"NavigationRegion3D") as NavigationRegion3D
	if region == null or region.navigation_mesh == null:
		return
	var map := get_world_3d().navigation_map
	var navmesh := region.navigation_mesh
	if not is_equal_approx(NavigationServer3D.map_get_cell_size(map), navmesh.cell_size):
		NavigationServer3D.map_set_cell_size(map, navmesh.cell_size)
	if not is_equal_approx(NavigationServer3D.map_get_cell_height(map), navmesh.cell_height):
		NavigationServer3D.map_set_cell_height(map, navmesh.cell_height)
