extends Node3D
## AI sandbox: a small store (aisles, checkout, produce, storage, break room) with
## StoreZones, patrol points, a baked navmesh, the Player stub, three coworkers and
## the monster. The layout is generated by build_ai_sandbox.gd; re-run it after
## changing the layout:
##   godot --headless --path . -s res://systems/monster/sandbox/build_ai_sandbox.gd
## Play: WASD, Shift sprint, mouse look (click), E hide in the break-room locker.
## Keys: T +1 hour, M manager task, I intercom to a random zone, L mimic lure,
##       K abduction, R reveal, H toggle this overlay.

const TaskSource := preload("res://systems/monster/sandbox/sandbox_task_source.gd")
const INTERCOM_LINE := "Could someone come to %s, please. Thank you."

@export var start_hour := 0.0
@export var show_overlay := true

var task_source: RefCounted          ## stand-in while the Tasks autoload is a stub
var _overlay: Label
var _rng := RandomNumberGenerator.new()
var _log: Array[String] = []


func _ready() -> void:
	_rng.randomize()
	GameState.world_root = self
	Tasks.reset()
	GameState.start_night()
	GameState.night_time = start_hour * GameState.SECONDS_PER_HOUR
	Tasks.begin_night()
	if Tasks.get_open_tasks().is_empty():
		task_source = TaskSource.new()
		for station: TaskStation in get_tree().get_nodes_in_group(&"task_station"):
			if station.basic_task:
				task_source.add_task(station, false, maxf(station.hold_time, 2.0))
		for coworker: Coworker in get_tree().get_nodes_in_group(&"coworker"):
			coworker.task_source = task_source
	Events.walkie_message.connect(_on_walkie)
	Events.intercom_announced.connect(func(message: String, _zone: StringName) -> void: _note("[INTERCOM] " + message))
	Events.monster_state_changed.connect(func(state: StringName) -> void: _note("monster -> " + String(state)))
	Events.coworker_missing.connect(func(who: String) -> void: _note("MISSING: " + who))
	Events.monster_sighted.connect(func() -> void: _note("monster sighted"))
	_build_overlay()


func _exit_tree() -> void:
	if GameState.world_root == self:
		GameState.world_root = null
	GameState.night_running = false


func _process(_delta: float) -> void:
	if _overlay == null or not _overlay.visible:
		return
	var lines: Array[String] = ["AI SANDBOX  %s" % GameState.get_clock_text()]
	var monster := GameState.monster as Monster
	if monster != null:
		lines.append(monster.get_debug_text())
	for coworker: Coworker in get_tree().get_nodes_in_group(&"coworker"):
		lines.append("%s: %s%s" % [coworker.employee_name, coworker.state,
			"  (" + coworker.current_task.title + ")" if coworker.current_task != null else ""])
	if GameState.player is Player:
		var player := GameState.player as Player
		lines.append("player hp %.0f%s" % [player.health, "  HIDDEN" if player.is_hidden else ""])
	lines.append("")
	lines.append_array(_log)
	lines.append("T +1h  M manager task  I intercom  L lure  K abduct  R reveal  H hide text")
	_overlay.text = "\n".join(lines)


func _unhandled_input(event: InputEvent) -> void:
	var key := event as InputEventKey
	if key == null or not key.pressed or key.echo:
		return
	var monster := GameState.monster as Monster
	match key.keycode:
		KEY_T:
			GameState.night_time = minf(GameState.night_time + GameState.SECONDS_PER_HOUR,
				GameState.SECONDS_PER_HOUR * GameState.END_HOUR - 1.0)
		KEY_M:
			_add_manager_task()
		KEY_I:
			var zones := get_tree().get_nodes_in_group(&"store_zone")
			var zone: StoreZone = zones[_rng.randi() % zones.size()]
			Events.intercom_announced.emit(INTERCOM_LINE % CoworkerLines.zone_phrase(zone.zone_id), zone.zone_id)
		KEY_L:
			if monster != null and not monster.try_mimic_lure():
				_note("lure: not now (seen, or busy)")
		KEY_K:
			if monster != null and not monster.try_abduction():
				_note("abduction: nobody out of sight and far away")
		KEY_R:
			if monster != null:
				monster.force_state(Monster.REVEAL)
		KEY_H:
			_overlay.visible = not _overlay.visible


func _add_manager_task() -> void:
	for station: TaskStation in get_tree().get_nodes_in_group(&"task_station"):
		if station.basic_task or station.is_active():
			continue
		var task: TaskData = task_source.add_task(station, true, maxf(station.hold_time, 2.0)) \
			if task_source != null else Tasks.add_manager_task(station, 120.0)
		if task != null:
			Events.intercom_announced.emit(INTERCOM_LINE % CoworkerLines.zone_phrase(station.zone), station.zone)
		return
	_note("no free station for a manager task")


func _on_walkie(speaker: String, message: String, _origin: Vector3, is_mimic: bool) -> void:
	_note("[RADIO] %s: %s%s" % [speaker, message, "   <- MIMIC" if is_mimic else ""])


func _note(text: String) -> void:
	_log.append(text)
	while _log.size() > 8:
		_log.pop_front()
	print(text)


func _build_overlay() -> void:
	var layer := CanvasLayer.new()
	add_child(layer)
	_overlay = Label.new()
	_overlay.position = Vector2(12, 8)
	_overlay.add_theme_color_override(&"font_color", Catalog.COLOR_CREAM)
	_overlay.add_theme_color_override(&"font_shadow_color", Color.BLACK)
	_overlay.add_theme_font_size_override(&"font_size", 14)
	_overlay.visible = show_overlay
	layer.add_child(_overlay)
