extends Node3D
## Greybox level root (docs/ARCHITECTURE.md §7 layout as plain boxes).
## The scene is GENERATED by levels/greybox/build_greybox.gd — edit the generator, not the .tscn:
##   godot --headless --path . -s res://levels/greybox/build_greybox.gd
##
## The navmesh is baked with 0.1 m cells so the 1.2 m doorways stay open for 0.4 m-radius
## agents (0.25 m cells round the radius up to 0.5 m and close them), and 0.1 m cell height so
## the 1.8 m agent height is exact. The navigation map must use the same cell size/height, so
## this sets them before the region registers its mesh.
##
## Shelf stock is not stored in the scene: every MultiMeshInstance3D named "ProductRun*" carries
## metadata (length, depth, levels, item sizes, palette, seed) and is filled here at load time.


func _enter_tree() -> void:
	var region := get_node_or_null(^"NavigationRegion3D") as NavigationRegion3D
	if region and region.navigation_mesh:
		var map := get_world_3d().navigation_map
		var navmesh := region.navigation_mesh
		if not is_equal_approx(NavigationServer3D.map_get_cell_size(map), navmesh.cell_size):
			NavigationServer3D.map_set_cell_size(map, navmesh.cell_size)
		if not is_equal_approx(NavigationServer3D.map_get_cell_height(map), navmesh.cell_height):
			NavigationServer3D.map_set_cell_height(map, navmesh.cell_height)


func _ready() -> void:
	for run in find_children("ProductRun*", "MultiMeshInstance3D", true, false):
		fill_product_run(run as MultiMeshInstance3D)


## Fills a run with boxes. Local frame: +X = outward (toward the aisle), +Z = along the
## shelf, y = board heights from the "levels" metadata.
static func fill_product_run(run: MultiMeshInstance3D) -> void:
	var rng := RandomNumberGenerator.new()
	rng.seed = int(run.get_meta(&"seed", 1))
	var length: float = run.get_meta(&"length", 1.0)
	var depth: float = run.get_meta(&"depth", 0.5)
	var levels: Array = run.get_meta(&"levels", [0.0])
	var palette: PackedColorArray = run.get_meta(&"palette", PackedColorArray([Color.GRAY]))
	var item_min: Vector3 = run.get_meta(&"item_min", Vector3(0.2, 0.15, 0.1))
	var item_max: Vector3 = run.get_meta(&"item_max", Vector3(0.4, 0.3, 0.25))
	var gap_chance: float = run.get_meta(&"gap_chance", 0.08)
	var transforms: Array[Transform3D] = []
	var colors: Array[Color] = []
	for level_y: float in levels:
		var z := 0.03
		while true:
			var size := Vector3(
				rng.randf_range(item_min.x, item_max.x),
				rng.randf_range(item_min.y, item_max.y),
				rng.randf_range(item_min.z, item_max.z))
			if z + size.z > length - 0.02:
				break
			if rng.randf() >= gap_chance:
				var origin := Vector3(depth - size.x * 0.5 - rng.randf_range(0.0, 0.04), level_y + size.y * 0.5, z + size.z * 0.5)
				transforms.append(Transform3D(Basis.from_scale(size), origin))
				colors.append(palette[rng.randi() % palette.size()].darkened(rng.randf_range(0.0, 0.3)))
			z += size.z + rng.randf_range(0.004, 0.025)
	var multimesh := MultiMesh.new()
	multimesh.transform_format = MultiMesh.TRANSFORM_3D
	multimesh.use_colors = true
	multimesh.mesh = BoxMesh.new()
	multimesh.instance_count = transforms.size()
	for i in transforms.size():
		multimesh.set_instance_transform(i, transforms[i])
		multimesh.set_instance_color(i, colors[i])
	run.multimesh = multimesh
