extends SceneTree
## Packs processed voice WAVs into QOA-compressed AudioStreamWAV .res files (about a fifth of
## the WAV size, the same data the WAV importer would ship) and writes the manifest
## res://assets/audio/voice/voice_manifest.gd that VoiceLines reads.
##   godot --headless --path . -s res://art_source/voice/pack_voices.gd -- <staging dir>
## The staging dir holds <id>.wav files plus index.json from process_voices.py.

const OUT_DIR := "res://assets/audio/voice"


func _initialize() -> void:
	_run.call_deferred()


func _run() -> void:
	await process_frame
	var args := OS.get_cmdline_user_args()
	if args.is_empty():
		push_error("usage: -- <staging dir>")
		quit(1)
		return
	var staging: String = args[0]
	var index: Variant = JSON.parse_string(FileAccess.get_file_as_string(staging.path_join("index.json")))
	if not index is Array:
		push_error("no index.json in " + staging)
		quit(1)
		return
	# Clear old clips so renamed/removed lines do not linger.
	for sub in DirAccess.get_directories_at(OUT_DIR):
		var dir := OUT_DIR.path_join(sub)
		for file in DirAccess.get_files_at(dir):
			if file.ends_with(".res"):
				DirAccess.remove_absolute(ProjectSettings.globalize_path(dir.path_join(file)))
	var manifest := PackedStringArray()
	var total_bytes := 0
	for entry: Dictionary in index:
		var stream := AudioStreamWAV.load_from_file(staging.path_join(String(entry["id"]) + ".wav"), {"compress/mode": 2})
		if stream == null:
			push_error("could not load " + String(entry["id"]))
			quit(1)
			return
		var sub_dir := OUT_DIR.path_join(String(entry["speaker"]).to_lower())
		DirAccess.make_dir_recursive_absolute(ProjectSettings.globalize_path(sub_dir))
		var path := sub_dir.path_join(String(entry["id"]) + ".res")
		var err := ResourceSaver.save(stream, path)
		if err != OK:
			push_error("save failed %s: %d" % [path, err])
			quit(1)
			return
		total_bytes += FileAccess.get_file_as_bytes(path).size()
		manifest.append("\t%s: \"%s\"," % [JSON.stringify(String(entry["key"])), path])
	var text := "extends RefCounted\n## GENERATED by art_source/voice/build_voices.sh -- do not edit by hand.\n" \
			+ "## Voice clip per exact line: \"channel|SPEAKER|mimic|text\" -> clip path.\n\n" \
			+ "const LINES := {\n" + "\n".join(manifest) + "\n}\n"
	var file := FileAccess.open(OUT_DIR.path_join("voice_manifest.gd"), FileAccess.WRITE)
	file.store_string(text)
	file.close()
	print("packed %d clips, %.2f MB" % [index.size(), total_bytes / 1048576.0])
	quit(0)
